_target_: torchrl.collectors.SyncDataCollector

create_env_fn: null
policy: null
frames_per_batch: 16
total_frames: 1_000_000
init_random_frames: 100
env_device: cpu
storing_device: cpu
policy_device: ${device}