defaults:
- transform@env.transform: default
- logger: wandb
- reward: none
- predictor: forward_inverse
- module: sac
- loss: soft_sac_loss
- optimizers: sac_adam
- collector: multiasync
- replay_buffer: default
- _self_

seed: 42
obs_modality: touch
train_steps: 200_000
init_rand_frames: 1_000
pbar_every: 1000
grad_log_every: 1000

eval:
  seed: 0
  is_on: true
  every: 10_000
  for: 1_000

env:
  seed: ${seed}
  num_envs: 8
  init_stats_iter: 1_000
  info_keys: null

device: ${get_device:} # custom resolver
save_models: true
save_dir: ${hydra:runtime.cwd}/models

logger:
  model_name: SAC
  experiment_name: touch

replay_buffer:
  shared: true
  prefetch: null
  batch_size: 4096

collector:
  frames_per_batch: 16