defaults:
- transforms@env.transforms: default
- logger: wandb
- reward: touch
- module: sac
- loss: soft_sac_loss
- optimizers: sac_adam
- collector: sync
- replay_buffer: default
- _self_

seed: 42

device: ${get_device:} # custom resolver
save_models: true
save_dir: ${hydra:runtime.cwd}/models

logger:
  model_name: SAC
  experiment_name: touch