defaults:
- default
- override collector: async
- override reward: none
- override predictor: forward_inverse
- _self_

obs_modality: touch
train_steps: 10_000
init_rand_frames: 500

eval:
  seed: 0
  is_on: true
  every: 1_000
  for: 1_000

env:
  num_envs: 1
  init_stats_iter: 100
  info_keys:
    - intrinsic_loss_fwd
    - intrinsic_loss_inv

save_models: false

replay_buffer:
  shared: false
  prefetch: null
  batch_size: 128
