_target_: babybench.predictors.ForwardInverseSurprisePredictor
feat_size: 256
in_keys:
  - touch
dtype: ${type:torch.float32}

feat_extractor:
  _target_: torchrl.modules.MLP
  out_features: ${predictor.feat_size}
  num_cells: [1024,512]
  activation_class: ${cls:torch.nn.ReLU} # custom resolver
  device: ${device}
  dropout: 0.0

forward_model:
  _target_: torchrl.modules.MLP
  out_features: ${predictor.feat_size}
  num_cells: [512,1024]
  activation_class: ${cls:torch.nn.ReLU} # custom resolver
  device: ${device}
  dropout: 0.0

inverse_model:
  _target_: torchrl.modules.MLP
  out_features: ${env_act_shape:}
  num_cells: [512,256]
  activation_class: ${cls:torch.nn.ReLU} # custom resolver
  device: ${device}
  dropout: 0.0

forward_loss_fn:
  _target_: torch.nn.CosineEmbeddingLoss
  margin: 0.0
  reduction: mean

inverse_loss_fn:
  _target_: torch.nn.MSELoss
  reduction: mean

optim:
  _partial_: true
  _target_: torch.optim.Adam
  lr: 1e-3

clip_grad: 1.0

action_low: ${env_act_space_low:}
action_high: ${env_act_space_high:}

beta: 0.2
eta: 0.1