_convert_: partial
module:
  _target_: torchrl.objectives.SACLoss
  actor_network: ${agent_policy_operator:} # custom resolver
  qvalue_network: ${agent_critic_operator:} # custom resolver
  num_qvalue_nets: 2
  loss_function: smooth_l1
  delay_actor: false
  delay_qvalue: true
  min_alpha: 0.1
  max_alpha: 1.0

value_estimator:
  gamma: 0.99

target_net_updater:
  _target_: torchrl.objectives.SoftUpdate
  loss_module: null
  eps: 0.995